---
title: "Milestone3_preparing_data"
output: html_document
---
```{r, message=FALSE}
library(readxl)
library(keras)
library(tensorflow)
library(dplyr)
library(magrittr)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
NonBilled <- read_excel("December Non-bill calls.xlsx", na = c("", "---"), n_max = 150)
Billed <- read_excel("Invoiced December.xlsx", na = c("", "---"), n_max = 150)
```

## Combining files

```{r}
newdata <- rbind(NonBilled, Billed)
colnames(newdata)
```

## Cleaning Data

```{r}
newdata1<- c('SR Address Line 1','SR City', 'SR Status','Activity Status', 'Charges Status', 'SR Coverage Hours__1', 'Br Region Desc', 'Activity Facts Call Num', 'Br Area Desc', 'SR Coverage Hours')
newdata <- newdata %>% select(-newdata1)

```
```{r}
newdata2<- c('Invoiced (Y/N)','Activity Type','Activity Trouble Code','Coverage Type','Base Call YN','SR Type','SR Device','SR Site','SR Owner (Q#)','SR Serial Number','Cash Vendor & Consumable Contracts')

```
```{r}
newdata <- newdata %>% mutate_at(newdata2, factor)
```
```{r}
call_text <-  use_series(newdata, `Call Text`)
billing_notes <-  use_series(newdata, `Billing Notes`)
item_desc <- use_series(newdata, `Item Desc`)
```

##Encoding Step

```{r}
coff <- list( MAX_WORDS = 12000,MAX_LEN = 200)
```

```{r}
lab <- newdata %>%
  use_series("Invoiced (Y/N)") %>%
  as.numeric() %>%
  subtract(1) %>%
  as.array()
dim(lab)
```

##Encoding call text variable

```{r}
calltext <- newdata %>% select(`Call Text`)
token1 <- keras::text_tokenizer(num_words = coff$MAX_WORDS) %>%
  keras::fit_text_tokenizer(calltext$`Call Text`)
seq1 <- texts_to_sequences(token1, calltext$`Call Text`)
index1 <- token1$word_index
cat("There're", length(index1), "unique words\n")
calltext <- pad_sequences(seq1, maxlen = coff$MAX_LEN)
cat("Tensor dimentions:", dim(calltext), "\n")
```

##Encoding Billing Notes variable

```{r}
billingnotes <- newdata %>% select(`Billing Notes`)
token2 <- keras::text_tokenizer(num_words = coff$MAX_WORDS) %>%
  keras::fit_text_tokenizer(billingnotes$`Billing Notes`)
seq2 <- texts_to_sequences(token2, billingnotes$`Billing Notes`)
index2 <- token2$word_index
cat("There're", length(index2), "unique words\n")
billingnotes <- pad_sequences(seq2, maxlen = coff$MAX_LEN)
cat("Tensor dimentions:", dim(billingnotes), "\n")

```

##Encoding Item Describtion variable

```{r}
itemdesc <- newdata %>% select(`Item Desc`)
token3 <- keras::text_tokenizer(num_words = coff$MAX_WORDS) %>%
  keras::fit_text_tokenizer(itemdesc$`Item Desc`)
seq3 <- texts_to_sequences(token3, itemdesc$`Item Desc`)
index3 <- token3$word_index
cat("There're", length(index3), "unique words\n")
itemdesc <- pad_sequences(seq3, maxlen = coff$MAX_LEN)
cat("Tensor dimentions:", dim(itemdesc), "\n")
```

```{r}
save.image(file = "data_preparing_file.rda")
save(newdata, coff, calltext,lab, billingnotes,itemdesc, file="data_preparing.rda")
```
