---
title: "Milestone3_Model"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
load("data_preparing.rda")
```

```{r}
library(keras)
library(dplyr)
library(magrittr)
```

```{r}
split_data <- function(data, train_size = 0.70) {
  smp_size = data %>%
    nrow() %>%
    multiply_by(train_size) %>%
    floor()
  return(data %>%
           nrow() %>%
           sample(x = seq_len(.), size = smp_size))}
```

## Call Text Model

```{r}
set.seed(100)
train_id <- split_data(calltext)

train1 <- calltext[train_id,]
val1 <- calltext[-train_id,]

train2 <- lab[train_id]
val2 <- lab[-train_id]
```

```{r}
calltext_model <- keras_model_sequential() %>% 
  layer_embedding(input_dim = coff$MAX_WORDS, output_dim = 50, input_length = coff$MAX_LEN) %>% 
  layer_flatten() %>% 
  layer_dense(units = 5) %>% 
  layer_dense(units = 4) %>% 
  layer_dense(units = 3) %>% 
  layer_dense(units = 1)
summary(calltext_model)
```

```{r}
calltext_model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc"))
opt <- calltext_model %>% fit(
  train1, train2,
  epochs = 10,
  batch_size = 30,
  validation_data = list(val1, val2))
plot(opt)

```

## Call Text Model Confusion Matrix

```{r}
cm <- calltext_model %>% predict_classes(val1)
table(val2,cm)
```

## Billing Notes Model

```{r}
set.seed(100)
train_id <- split_data(billingnotes)

train1 <- billingnotes[train_id,]
val1 <- billingnotes[-train_id,]

train2 <- lab[train_id]
val12 <- lab[-train_id]

```

```{r}
billingnotes_model <- keras_model_sequential() %>% 
  layer_embedding(input_dim = coff$MAX_WORDS, output_dim = 233, input_length = coff$MAX_LEN) %>% 
  layer_flatten() %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 1, activation = "sigmoid")
summary(billingnotes_model)
```

```{r}
billingnotes_model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc"))
opt <- billingnotes_model %>% fit(
  train1, train2,
  epochs = 10,
  batch_size = 32,
  validation_data = list(val1, val2))
plot(opt)
```

## Billing Notes Model Confusion Matrix
```{r}
cm <- billingnotes_model %>% predict_classes(val1)
table(val2,cm)
```

## Item Description Model

```{r}
set.seed(100)
train_id <- split_data(itemdesc)

train1 <- itemdesc[train_id,]
val1 <- itemdesc[-train_id,]

train2 <- lab[train_id]
val2 <- lab[-train_id]
```

```{r}
itemdesc_model <- keras_model_sequential() %>% 
  layer_embedding(input_dim = coff$MAX_WORDS, output_dim = 107, input_length = coff$MAX_LEN) %>% 
  layer_flatten() %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 30, activation = "sigmoid") %>% 
  layer_dense(units = 1, activation = "sigmoid")
summary(itemdesc_model)
```

```{r}
itemdesc_model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc"))
opt <- itemdesc_model %>% fit(
  train1, train2,
  epochs = 10,
  batch_size = 32,
  validation_data = list(val1, val2))
plot(opt)
```

## Item Description Confusion Matrix

```{r}
cm <- itemdesc_model %>% predict_classes(val1)
table(val2,cm)
```

